# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b84370dbac39c87987203689a50a36f37dc864bab003e101998f6d4527f7ea150e8ee7c985a71a1557791402c6cb4a0baff6f00b074f584980274e17b9789c4

test:
  secret_key_base: c5f4cff834b2db2599b1a3988c9852e6cd26e0968f9de1af522cf9e8f7b6e028e452874a2697df197fe957658ddda9d2e3a386ae227eac923a02b0cbdd8c8966

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
